### ISSUE TITLE
Crash when inputting certain command

### ISSUE THREAD

**Issue by IrrelevantGaymer** [JoachimCoenen/Datapack-Editor#52]
Whenever you try to type "if block ~ ~ ~", the program crashes when typing the third tilde.  This is the error log form the terminal.  I am getting this error for v0.8.0-alpha.

scheduling redrawLater for '<ParsedDocument at {test.mcfunction}>'; cause = onErrorsChanged
scheduling redrawLater for '<basePlugins.documentErrors.DocumentErrorsGUI object at 0x0000015F3BC89A20>'; cause = onErrorsChanged
Traceback (most recent call last):
  File "base\gui\documentLexer.py", line 259, in styleText
  File "base\gui\documentLexer.py", line 273, in actuallyStyleText
  File "C:\Users/dharm/AppData/Local/Temp/_MEI32522/corePlugins/mcFunction\mcFunctionStyler.py", line 101, in styleNode
    return self.styleMCFunction(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/dharm/AppData/Local/Temp/_MEI32522/corePlugins/mcFunction\mcFunctionStyler.py", line 119, in styleMCFunction
    end = self.styleCommand(child)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/dharm/AppData/Local/Temp/_MEI32522/corePlugins/mcFunction\mcFunctionStyler.py", line 127, in styleCommand
    return self.styleArguments(command.next)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/dharm/AppData/Local/Temp/_MEI32522/corePlugins/mcFunction\mcFunctionStyler.py", line 135, in styleArguments
    span = self.styleArgument(argument)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/dharm/AppData/Local/Temp/_MEI32522/corePlugins/mcFunction\mcFunctionStyler.py", line 155, in styleArgument
    styler.style(argument)
  File "C:\Users/dharm/AppData/Local/Temp/_MEI32522/corePlugins/datapackVersions\commands\argumentStylers.py", line 195, in style
    styleForeignNode2(self, value.blockId, value.blockId.span)
                                           ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'span'

I see nothing in the logfile that looks particularly helpful here, just a bunch of GUI Redraws.

**Comment by JoachimCoenen** [comment]
Thank you. I'll look into it.

**Comment by JoachimCoenen** [comment]
fixed in 0.8.6-alpha
